apiVersion: v1
kind: Namespace
metadata:
  name: web-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-db
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: web-app
  labels: {app: employees}
spec:
  containers:
  - name: webapp-container
    image: ladunuthala/php-mysql-webapp:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-db
  labels: {app: mysql}
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"